global using ff1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileFunctions;
global using CommonBasicLibraries.CollectionClasses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.CSharpCodeWriters;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
